#!/bin/python3
import json
from os.path import join

cards = {}
manifest = json.loads(open(join('..', 'CWCore', 'cards', 'manifest.json'), 'r').read())
for card_key in manifest['cards']:
    card = json.loads(open(join('..', 'CWCore', 'cards', card_key + '.json'), 'r').read())
    card_name = card['Name']
    cards[card_name] = 5
open(join('decks', 'all.json'), 'w').write(json.dumps({
    'Cards': cards,
    'Landscapes': {}
}, indent=4))